version: '3.7'

services:
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

  postgres:
    image: postgres:latest  # Используем официальный образ PostgreSQL
    container_name: postgres-container  # Указываем имя контейнера для БД
    environment:
      POSTGRES_USER: ${DB_USERNAME}  # Имя пользователя
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Пароль
      POSTGRES_DB: ${DB_NAME}  # Название базы данных
    ports:
      - "5432:5432"  # Пробрасываем порт PostgreSQL на локальную машину
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Добавляем volume для сохранения данных
    networks:
      - mynetwork  # Добавляем в сеть для связи с приложением

volumes:
  minio_storage:
  postgres_data:  # Том для хранения данных БД (чтобы они не удалялись при перезапуске контейнера)

networks:
  mynetwork:  # Создаем кастомную сеть для взаимодействия контейнеров
